name: oci-terraform-build-demo
on:
  push:
    branches:
      - github-actions-tf
    tags:
      - "v*"
jobs:
  build-with-terraform:
    name: Build With Terraform
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2