name: oci-resource-manager-build-demo
on:
  push:
    branches:
      - github-actions-resource-manager
    tags:
      - "v*"
jobs:
  build-resource-manager:
    name: Build Resource Manager
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2